<?php

namespace servicomBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use FOS\UserBundle\Form\Type\RegistrationFormType as BaseRegistrationFormType;

class FRepresentType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('reNo')
            ->add('reNom')
            ->add('rePrenom')
            ->add('reRegion')
            ->add('reTelephone')
            ->add('reEmail')
            ->add('reDatecreation')
            ->add('imageName');

    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'servicomBundle\Entity\FRepresent'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'servicombundle_frepresent';
    }

    public function  getParent()
    {
        return BaseRegistrationFormType::class ; // TODO: Change the autogenerated stub
    }

}
